version: '3.5'

services:
  #userdash:
  #  container_name: user-management-dashboard
  #  build:
  #    context: ./user-management-dashboard
  #    args:
  #      - APP_NAME=ODK dev
  #  ports:
  #      - "8070:80"
  
  #frame-analyzer:
  #  container_name: odk-frame-analyzer
  #  build:
  #    context: https://github.com/haiderlawati/odk-stack/tree/main/odk-frame-analyzer
  #  ports:
  #    - "8090:80"
  #    - "8099:8099"

  #app:
  #  container_name: odk-app
  #  build:
  #    context: https://github.com/haiderlawati/odk-stack/tree/main/odk-app
  #    args:
  #      - APP_NAME=ODK dev
  #      - MODE=production
  #  ports:
  #    - "8070:80"

  #api:
  #  container_name: odk-api
  #  build: https://github.com/haiderlawati/odk-stack/tree/main/odk-api
  #  env_file:
  #    - https://github.com/haiderlawati/odk-stack/tree/main/odk-api/.global.env
  #    - https://github.com/haiderlawati/odk-stack/tree/main/odk-api/.development.env
  #  ports:
  #    - "8080:80"

  db:
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=odk
      - POSTGRES_PASSWORD=development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rmq:
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=odk
      - RABBITMQ_DEFAULT_PASS=development
    ports:
       - "8081:8080"
       - "5672:5672"
       - "15672:15672"

volumes:
  postgres-data:
