version: '3'

services:
  
  proxy:
    container_name: odk-proxy
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /nginx/error.log:/etc/nginx/error_log.log
      - /nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"
  
  app:
    container_name: odk-app
    build: ./odk-app
    depends_on:
      - api
    expose:
      - "80"

  api:
    container_name: odk-api
    build: ./odk-api
    depends_on:
      - db
      - rmq
    env_file:
      - ./odk-api/.global.env
      - ./odk-api/.production.env
    environment:
      - DATABASE_URL
      - BROKER_URL
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
      - SECRET_KEY
    expose:
      - "80"

  db:
    container_name: odk-db
    build: ./postgres_dockerfiles
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/pgdata
    ports:
        - "5432:5432"
    volumes:
        - /pgdata-docker:/pgdata
    logging:
       options:
         max-size: 50m

  rmq:
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
      - "3389:5672"
      - "15672:15672"