version: '3'

services:

  app:
    container_name: odk-app
    build: ./odk-app
    environment:
      - VUE_APP_API_HTTP_URL=/api
    depends_on:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - odb-network

  api:
    container_name: odk-api
    build: ./odk-api
    environment:
      - API_PREFIX=/api
      - JWT_SECRET_KEY=A_SIMPLE_SECRET_FOR_DEVELOPMENT
      - DATABASE_CONNECTION_STRING=postgresql://postgres:mysecretpassword@odk-db/postgres
      - RMQ_USER=user
      - RMQ_PASSWORD=password
      - RMQ_URL=localhost
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./odk-api:/app
    depends_on:
      - db
    networks:
      - odb-network

  rmq:
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
       - "8081:8080"
       - "5672:5672"
       - "15672:15672"
    expose:
      - "15672"
      - "8080"
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - odb-network

  db:
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    expose:
      - "5432"
    logging:
       options:
         max-size: 50m
    networks:
      - odb-network
    volumes:
      - ./pgdata:/pgdata
networks:
  odb-network:

