version: '3'

services:

  app:
    restart: always
    container_name: odk-proxy
    image: nginx
    depends_on:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
      - ./odk-app/dist:/dist

  # dashboard:
  #   restart: always
  #   container_name: odk-dash
  #   image: nginx
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./logs:/var/log/nginx
  #     - ./odk-dashboard/dist:/dist

  api:
    restart: always
    container_name: odk-api
    build: ./odk-api
    depends_on:
      - db
      - rmq
    env_file:
      - ./env_files/odk-api.env
    ports:
      - "8080:80"
    volumes:
    - ./odk-api:/app

  rmq:
    restart: always
    container_name: odk-rmq
    image: rabbitmq:3-management
    env_file:
      - ./env_files/odk-rmq.env
    ports:
      - "8081:8080"
      - "5672:5672"
      - "15672:15672"

  db:
    restart: always
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    env_file:
      - ./env_files/odk-db.env
    environment:
        - PGDATA=/pgdata
    ports:
        - "5432:5432"
    volumes:
        - ./pgdata:/pgdata
    logging:
       options:
         max-size: 50m
