version: '3'

services:

  proxy:
    restart: always
    container_name: odk-proxy
    image: nginx
    ports:
      - "81:80"
    #  - "443:443"
    volumes:
     - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    #  - ./certs:/certs:ro
    #  - ./domains:/domains
     - ./logs:/var/log/nginx
     - ./odk-streaming-app/dist:/dist
     - ./odk-dashboard:/odk-dash

  api:
    restart: always
    container_name: odk-api
    build: ./odk-api
    environment:
        - TODO=todo
    ports:
      - "8080:80"
    volumes:
    - ./odk-api:/app

  rmq:
    restart: always
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=odk
      - RABBITMQ_DEFAULT_PASS=rmqodk
    ports:
      - "8081:8080"
      - "5672:5672"

  db:
    restart: always
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    environment:
        - PGDATA=/pgdata
        - POSTGRES_NAME=odk
        - POSTGRES_HOST=db
        - POSTGRES_USER=odk
        - POSTGRES_PASSWORD=pgodk
    ports:
        - "5432:5432"
    volumes:
        - ./pgdata:/pgdata
    logging:
       options:
         max-size: 50m
