version: '3'

services:

  proxy:
    restart: always
    container_name: odk-proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
     - ./certs:/certs:ro
     - ./domains:/domains
     - ./logs:/var/log/nginx
     - ./odk-app/dist:/app-dist
     - ./odk-dashboard/dist:/dash-dist
     - ./odk-website/dist:/website-dist    

  api:
    restart: always
    container_name: odk-api
    build: ./odk-api
    env_file: 
      - ./env_files/odk-api.env
    ports:
      - "8080:80"
    volumes:
      - ./odk-api:/app
      - ./frames-analysed:/frames-analysed
  
  rmq:
    restart: always
    container_name: odk-rmq
    image: rabbitmq:3-management
    env_file:
      - ./env_files/odk-rmq.env
    ports:
      - "8081:8080"
      - "5672:5672"

  db:
    restart: always
    container_name: odk-pg
    image: mdillon/postgis:10-alpine
    env_file:
      - ./env_files/odk-db.env
    environment:
        - PGDATA=/pgdata
    ports:
        - "5432:5432"
    volumes:
        - ./pgdata:/pgdata
    logging:
       options:
         max-size: 50m

  email:
    restart: always
    container_name: odk-email
    build: ./odk-website/server
    env_file:
      - ./odk-website/server/.env
    ports:
      - "3000:3000"

    
