version: "3.5"

services:
  app:
    container_name: odk-app
    build:
      context: ./odk-app
      args:
        - APP_NAME=ODK stage
        - MODE=staging
    ports:
      - "8000:80"
    networks:
      reversed-proxy:
        ipv4_address: 192.168.100.10

  api:
    container_name: odk-api
    build: ./odk-api
    environment:
      - DATABASE_URL=postgresql://odk:staging@db/odk
      - BROKER_URL=amqp://odk:staging@rmq
      - SECRET_KEY=notasecretkey
      - ADMIN_EMAIL=admin@staging.com
      - ADMIN_PASSWORD=admin
    env_file:
      - ./odk-api/.global.env
      - ./odk-api/.staging.env
    ports:
      - "8080:80"
    networks:
      default:
      reversed-proxy:
        ipv4_address: 192.168.100.20

  db:
    container_name: odk-db
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=odk
      - POSTGRES_PASSWORD=staging
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgis-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  rmq:
    container_name: odk-rmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=odk
      - RABBITMQ_DEFAULT_PASS=staging
    ports:
      - "8090:8080"
      - "3389:5672"
      - "15672:15672"
    networks:
      - default

volumes:
  postgis-data:

networks:
  reversed-proxy:
    external: true
    name: reversed-proxy-network
