stages:
    - build
    - test
    - deploy

build_server:
    stage: build
    script:
        - docker-compose -f docker-compose.ci.yml stop fastapi-server
        - docker-compose -f docker-compose.ci.yml build fastapi-server

deploy_server:
    stage: deploy
    # Using `needs` here breaks this child-pipeline for some reason, altough its included in the official documentation of GitLab
    # needs: build_server
    script:
        - docker-compose -f docker-compose.ci.yml up -d fastapi-server