stages:
    - build
    - test
    - deploy

build_server:
    stage: build
    script:
        - docker-compose -f docker-compose.ci.yml stop fastapi-server
        - docker-compose -f docker-compose.ci.yml build fastapi-server

deploy_server:
    stage: deploy
    # Using `needs` here breaks this child-pipeline for some reason, altough its included in the official documentation of GitLab:
    # - https://docs.gitlab.com/ee/ci/pipelines/pipeline_architectures.html#child--parent-pipelines
    # needs: build_server
    script:
        - docker-compose -f docker-compose.ci.yml up -d --no-deps fastapi-server