apiVersion: v1
kind: Service
metadata:
  name: frame-analyzer
spec:
  ports:
    - port: 80
  selector:
    app: frame-analyzer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-analyzer
spec:
  selector:
    matchLabels:
      app: frame-analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: frame-analyzer
    spec:
      containers:
        - name: frame-analyzer
          image: oorcontainerregistry.azurecr.io/oor/frame-analyzer-worker
          env:
            - name: RMQ_USERNAME
              value: "user"
            - name: RMQ_PASSWORD
              value: ""
          ports:
            - containerPort: 80
              name: frame-analyzer
